//https://adventofcode.com/2023/day/8
namespace AdventOfCode.Year2023
{
    class Day8
    {
        Dictionary<string, (string left, string right)> nodes;
        char[] instructions;

        public Day8()
        {
            nodes = [];
            instructions = [];
        }

        public void Run()
        {
            var start = DateTime.Now;

            GetData();

            long steps = GetStepsToEnd("AAA", "ZZZ");

            Console.WriteLine($"Total steps: {steps}");
            Console.WriteLine($"{(DateTime.Now - start).TotalMilliseconds}ms");

            start = DateTime.Now;

            List<long> stepsToEnd = [];

            foreach (var node in nodes)
            {
                if (node.Key[^1] == 'A')
                {
                    stepsToEnd.Add(GetStepsToEnd(node.Key, "Z"));
                }
            }

            steps = FindLCM(stepsToEnd);

            Console.WriteLine($"Total steps: {steps}");
            Console.WriteLine($"{(DateTime.Now - start).TotalMilliseconds}ms");
        }

        long GetStepsToEnd(string nextNode, string endNode)
        {
            var instructionIndex = 0;
            long steps = 0;

            while (true)
            {
                var instruction = instructions[instructionIndex];

                var node = nodes[nextNode];
                nextNode = instruction == 'L' ? node.left : node.right;

                instructionIndex++;

                if (instructionIndex == instructions.Length)
                {
                    instructionIndex = 0;
                }

                steps++;

                if (nextNode.EndsWith(endNode))
                    break;
            }

            return steps;
        }

        static long GCD(long n1, long n2)
        {
            if (n2 == 0)
            {
                return n1;
            }
            else
            {
                return GCD(n2, n1 % n2);
            }
        }

        static long LCM(long a, long b)
        {
            return (a / GCD(a, b)) * b;
        }

        static long FindLCM(List<long> numbers)
        {
            long result = numbers[0];
            for (var i = 1; i < numbers.Count; i++)
            {
                result = LCM(result, numbers[i]);
            }
            return result;
        }

        void AddNode(string key, (string left, string right) value)
        {
            nodes.Add(key, value);
        }

        void GetData()
        {
            instructions = "LRLRRRLRRLRRRLRRRLLLLLRRRLRLRRLRLRLRRLRRLRRRLRLRLRRLLRLRRLRRLRRLRRRLLRRRLRRRLRRLRLLLRRLRRRLRLRRLRRRLRRLRLLLRRRLRRLRRLRRRLRRRLRRRLRLRLRLRRRLRRRLLLRRLLRRRLRLRLRRRLRRRLRRLRRRLRLRLLRRRLRLRRLRLRLRRLLLRRRLRRRLRRLRRLRLRRLLRRLRRRLRRRLLRRRLRRLRLLRRLRLRRLLRRRLLLLRRLRRRLRLRRLLRLLRRRLLRRLLRRRLRRRLRRLLRLRLLRRLLRLLLRRRR".ToCharArray();

            AddNode("FCG", ("PLG", "GXC"));
            AddNode("PQT", ("SQK", "GHP"));
            AddNode("NVS", ("TPQ", "PPB"));
            AddNode("CTR", ("SXS", "KCV"));
            AddNode("FNM", ("KHG", "FLD"));
            AddNode("TFH", ("CLD", "CLD"));
            AddNode("MLQ", ("QQL", "JVK"));
            AddNode("LQR", ("TFH", "RRM"));
            AddNode("QKX", ("VPR", "BHD"));
            AddNode("QQL", ("VBD", "CPM"));
            AddNode("QST", ("HPC", "DFJ"));
            AddNode("QBX", ("HPH", "BTM"));
            AddNode("TVB", ("SHJ", "GMF"));
            AddNode("HJN", ("CGJ", "QXT"));
            AddNode("PGV", ("RXT", "DQP"));
            AddNode("TPN", ("TQR", "LJR"));
            AddNode("BHV", ("TGL", "GJH"));
            AddNode("DDF", ("XLH", "TDQ"));
            AddNode("XMK", ("XVN", "RJP"));
            AddNode("HXH", ("JVM", "CVB"));
            AddNode("SFX", ("VNH", "BFS"));
            AddNode("TRF", ("HVJ", "DKF"));
            AddNode("GGQ", ("NNP", "PBL"));
            AddNode("KQX", ("VXK", "FSF"));
            AddNode("KGL", ("QSJ", "CBM"));
            AddNode("CLC", ("MCJ", "JGQ"));
            AddNode("GFF", ("JBG", "TVR"));
            AddNode("FQT", ("CMR", "CKG"));
            AddNode("HVJ", ("FXB", "GBP"));
            AddNode("KTF", ("PKG", "JCL"));
            AddNode("BLF", ("QQL", "JVK"));
            AddNode("TVN", ("QNN", "DPQ"));
            AddNode("KVX", ("XNV", "CJF"));
            AddNode("GDK", ("DVX", "RKS"));
            AddNode("CHS", ("VCL", "PSG"));
            AddNode("LFS", ("SNS", "NTG"));
            AddNode("NCR", ("LFV", "DRN"));
            AddNode("NLJ", ("RCR", "XCF"));
            AddNode("SRD", ("LGT", "PRS"));
            AddNode("FQC", ("GBX", "RGQ"));
            AddNode("SJH", ("CKG", "CMR"));
            AddNode("BQP", ("PPP", "HGT"));
            AddNode("LJR", ("FPV", "FQD"));
            AddNode("XTP", ("PDT", "MTX"));
            AddNode("RDG", ("JRL", "MFF"));
            AddNode("TFF", ("MJQ", "MVB"));
            AddNode("NGS", ("BDG", "KHS"));
            AddNode("GXT", ("QSJ", "CBM"));
            AddNode("VVD", ("HJJ", "RNK"));
            AddNode("FRL", ("CHS", "JNV"));
            AddNode("RQS", ("CFM", "SKM"));
            AddNode("PRS", ("VTG", "PRR"));
            AddNode("FCD", ("VTN", "DJQ"));
            AddNode("PDT", ("DST", "DST"));
            AddNode("MND", ("MFV", "GDR"));
            AddNode("GJG", ("TMJ", "HPJ"));
            AddNode("JSL", ("DDN", "JPZ"));
            AddNode("DNX", ("RHD", "LKM"));
            AddNode("BGM", ("GFC", "JTD"));
            AddNode("BPC", ("BMN", "BKQ"));
            AddNode("PPB", ("BFT", "PVH"));
            AddNode("VRK", ("TCL", "JDS"));
            AddNode("MBT", ("CBB", "JMM"));
            AddNode("JGQ", ("GGQ", "DFH"));
            AddNode("BGP", ("MGH", "VHG"));
            AddNode("GGR", ("TCX", "QLG"));
            AddNode("NCD", ("XDT", "SSK"));
            AddNode("TDQ", ("VPK", "HCF"));
            AddNode("PND", ("BKV", "THD"));
            AddNode("RJP", ("KRV", "FQN"));
            AddNode("MFZ", ("MRL", "MFK"));
            AddNode("TCM", ("RMM", "CLB"));
            AddNode("SDF", ("LTS", "RVQ"));
            AddNode("KGS", ("CTR", "SJQ"));
            AddNode("SFK", ("SDF", "HPF"));
            AddNode("DJC", ("MKF", "PNR"));
            AddNode("DPF", ("KBH", "QQX"));
            AddNode("VQJ", ("FVB", "XPK"));
            AddNode("CGX", ("MLQ", "BLF"));
            AddNode("GBS", ("DJC", "XXQ"));
            AddNode("JSV", ("RMR", "QFK"));
            AddNode("KHS", ("HSQ", "PTD"));
            AddNode("MKG", ("NLJ", "MHQ"));
            AddNode("CXQ", ("BDG", "KHS"));
            AddNode("RRQ", ("FCT", "CDT"));
            AddNode("JSK", ("LBC", "CPT"));
            AddNode("VSM", ("RGM", "VMR"));
            AddNode("NNP", ("SRD", "VNQ"));
            AddNode("PRR", ("GMX", "KQX"));
            AddNode("HNP", ("GQJ", "DGS"));
            AddNode("PKB", ("KBL", "HXJ"));
            AddNode("MFS", ("RMK", "JBX"));
            AddNode("RMM", ("MFG", "BPS"));
            AddNode("PJM", ("SFK", "HLG"));
            AddNode("BCH", ("SRK", "LSG"));
            AddNode("VNQ", ("LGT", "PRS"));
            AddNode("LTC", ("TJX", "DQD"));
            AddNode("CKG", ("NJG", "GMJ"));
            AddNode("RPS", ("RXT", "DQP"));
            AddNode("CCV", ("DPB", "JQT"));
            AddNode("JDF", ("CFF", "XFB"));
            AddNode("LQX", ("KBD", "TVD"));
            AddNode("VLL", ("FMK", "LCD"));
            AddNode("RTB", ("NTG", "SNS"));
            AddNode("FBF", ("QTH", "QFV"));
            AddNode("CBB", ("VJK", "BHB"));
            AddNode("BCL", ("LJR", "TQR"));
            AddNode("JDS", ("SPS", "HRL"));
            AddNode("HHB", ("RHD", "LKM"));
            AddNode("PLG", ("RBV", "NJD"));
            AddNode("RNB", ("VMR", "RGM"));
            AddNode("CJT", ("HJJ", "RNK"));
            AddNode("JVK", ("VBD", "CPM"));
            AddNode("HXJ", ("JTL", "PFD"));
            AddNode("JGX", ("XMV", "RHF"));
            AddNode("FGT", ("LFR", "JSK"));
            AddNode("MJQ", ("BVP", "BXM"));
            AddNode("DFJ", ("MRS", "LTC"));
            AddNode("GNG", ("DPB", "JQT"));
            AddNode("VCA", ("XFL", "JSV"));
            AddNode("KLR", ("LTN", "BXH"));
            AddNode("VGN", ("DGS", "GQJ"));
            AddNode("DVX", ("JXX", "XSH"));
            AddNode("BTN", ("PFP", "FRL"));
            AddNode("DTM", ("DVD", "FCF"));
            AddNode("SVN", ("PBF", "GXR"));
            AddNode("RCC", ("BTB", "CBD"));
            AddNode("GMJ", ("FCH", "CSP"));
            AddNode("DVS", ("FSV", "TVP"));
            AddNode("RLG", ("QML", "XGD"));
            AddNode("CVV", ("HHB", "DNX"));
            AddNode("NRG", ("NFG", "DNL"));
            AddNode("PQC", ("RNG", "KTF"));
            AddNode("KGG", ("DMD", "HQG"));
            AddNode("JNV", ("PSG", "VCL"));
            AddNode("SNS", ("CGX", "MBK"));
            AddNode("FRA", ("MFK", "MRL"));
            AddNode("BPN", ("QQX", "KBH"));
            AddNode("HCQ", ("XMK", "JDV"));
            AddNode("RDD", ("JGB", "VHQ"));
            AddNode("HTF", ("VLX", "RQV"));
            AddNode("XFH", ("DPH", "RGG"));
            AddNode("LBC", ("JTV", "DTK"));
            AddNode("RBP", ("LLL", "MND"));
            AddNode("GDV", ("SHJ", "GMF"));
            AddNode("MJV", ("JGV", "JGV"));
            AddNode("BQR", ("FPK", "HSS"));
            AddNode("XDT", ("BTN", "FXF"));
            AddNode("NGM", ("NTF", "BDN"));
            AddNode("HPP", ("FQX", "FGT"));
            AddNode("JPC", ("JHC", "PPH"));
            AddNode("GCV", ("CCS", "TCM"));
            AddNode("VHQ", ("PBR", "GVP"));
            AddNode("MDD", ("GGR", "LXC"));
            AddNode("HSQ", ("CKV", "KGS"));
            AddNode("PPP", ("DLP", "HPP"));
            AddNode("SNA", ("BKK", "FNM"));
            AddNode("VLS", ("DPH", "RGG"));
            AddNode("JGB", ("PBR", "GVP"));
            AddNode("FPK", ("RGS", "XKQ"));
            AddNode("LVB", ("XMC", "MNX"));
            AddNode("FDP", ("PFR", "GFP"));
            AddNode("NKS", ("PCH", "TJR"));
            AddNode("VLX", ("TLH", "KFD"));
            AddNode("DLT", ("HGV", "XJR"));
            AddNode("MBK", ("MLQ", "BLF"));
            AddNode("RNG", ("PKG", "PKG"));
            AddNode("BKV", ("DXB", "GDQ"));
            AddNode("LLL", ("GDR", "MFV"));
            AddNode("LNN", ("MVG", "CKJ"));
            AddNode("FXH", ("TCM", "CCS"));
            AddNode("TPQ", ("BFT", "PVH"));
            AddNode("MRH", ("CJR", "TFF"));
            AddNode("MVG", ("BQP", "DXC"));
            AddNode("LLN", ("VTN", "DJQ"));
            AddNode("MLS", ("THD", "BKV"));
            AddNode("HFR", ("HNP", "VGN"));
            AddNode("XNF", ("PVL", "TPD"));
            AddNode("JQT", ("DVS", "PST"));
            AddNode("LNH", ("FHQ", "SPG"));
            AddNode("MBR", ("LQR", "VPM"));
            AddNode("KNV", ("SKG", "CKF"));
            AddNode("JCV", ("XMV", "RHF"));
            AddNode("JQJ", ("TCQ", "BGM"));
            AddNode("SQF", ("NRG", "HDK"));
            AddNode("FHF", ("NNQ", "PKB"));
            AddNode("BDG", ("HSQ", "PTD"));
            AddNode("PBT", ("JRL", "MFF"));
            AddNode("LNS", ("TCQ", "BGM"));
            AddNode("PTD", ("CKV", "KGS"));
            AddNode("LHX", ("GRM", "XJQ"));
            AddNode("NXN", ("SFX", "NQC"));
            AddNode("VSZ", ("XFS", "DHL"));
            AddNode("DPG", ("JTS", "VBG"));
            AddNode("QTH", ("DLT", "JNS"));
            AddNode("PMG", ("TCL", "JDS"));
            AddNode("CCD", ("FCG", "GPJ"));
            AddNode("SSP", ("HTF", "MNV"));
            AddNode("STX", ("HPC", "DFJ"));
            AddNode("KSR", ("GKB", "TSX"));
            AddNode("KDP", ("XGR", "LLK"));
            AddNode("NNQ", ("HXJ", "KBL"));
            AddNode("TPM", ("PDT", "PDT"));
            AddNode("SJQ", ("KCV", "SXS"));
            AddNode("PJH", ("BPN", "DPF"));
            AddNode("JBG", ("FPN", "XBP"));
            AddNode("XQQ", ("TLR", "TLR"));
            AddNode("XJL", ("FTX", "DXR"));
            AddNode("RXT", ("RMD", "KVX"));
            AddNode("CLD", ("NTK", "NTK"));
            AddNode("SDM", ("MRH", "TGC"));
            AddNode("RQV", ("TLH", "KFD"));
            AddNode("NDL", ("VDT", "VDT"));
            AddNode("CCT", ("QFV", "QTH"));
            AddNode("LXL", ("VGH", "FRM"));
            AddNode("TJR", ("KGL", "GXT"));
            AddNode("VBD", ("RSG", "NCR"));
            AddNode("XBG", ("BHV", "NPX"));
            AddNode("JTS", ("QDH", "CST"));
            AddNode("BFT", ("JDF", "MXT"));
            AddNode("XLH", ("HCF", "VPK"));
            AddNode("XBP", ("GCV", "FXH"));
            AddNode("JPF", ("RNG", "KTF"));
            AddNode("HHN", ("TMJ", "HPJ"));
            AddNode("FSV", ("GMC", "HJN"));
            AddNode("XFB", ("JRN", "RDD"));
            AddNode("JPZ", ("FNM", "BKK"));
            AddNode("BBP", ("KDP", "KKM"));
            AddNode("TGL", ("TGX", "XRF"));
            AddNode("JCL", ("JDT", "JDP"));
            AddNode("RRS", ("XPK", "FVB"));
            AddNode("NSB", ("MCJ", "JGQ"));
            AddNode("DMD", ("GFG", "FDP"));
            AddNode("FFX", ("VBG", "JTS"));
            AddNode("XRF", ("XFH", "VLS"));
            AddNode("LSG", ("MFX", "CVC"));
            AddNode("BJZ", ("FNK", "QKX"));
            AddNode("DLP", ("FGT", "FQX"));
            AddNode("JDV", ("RJP", "XVN"));
            AddNode("HDK", ("DNL", "NFG"));
            AddNode("GQP", ("NQC", "SFX"));
            AddNode("NFG", ("PMG", "VRK"));
            AddNode("CSP", ("GDP", "NDV"));
            AddNode("BKK", ("FLD", "KHG"));
            AddNode("SCK", ("KKM", "KDP"));
            AddNode("DXR", ("SCK", "BBP"));
            AddNode("JVG", ("PBT", "RDG"));
            AddNode("GSV", ("QTK", "JNT"));
            AddNode("QXT", ("BPC", "NXQ"));
            AddNode("GDQ", ("LFJ", "KSF"));
            AddNode("NHG", ("VVD", "CJT"));
            AddNode("DHL", ("LNH", "RPP"));
            AddNode("NFS", ("JGV", "MFZ"));
            AddNode("FCS", ("BTB", "CBD"));
            AddNode("JGH", ("VHP", "RMG"));
            AddNode("VQC", ("GDC", "VKQ"));
            AddNode("PCH", ("KGL", "GXT"));
            AddNode("LGT", ("PRR", "VTG"));
            AddNode("PFV", ("QCC", "VSZ"));
            AddNode("QQX", ("FTV", "LBD"));
            AddNode("QFV", ("JNS", "DLT"));
            AddNode("SCN", ("RVX", "RBP"));
            AddNode("QRH", ("BCL", "TPN"));
            AddNode("GBX", ("VRH", "CPG"));
            AddNode("NTF", ("RBK", "RRN"));
            AddNode("NDQ", ("MBR", "RDL"));
            AddNode("KCP", ("GFF", "DDG"));
            AddNode("JBX", ("JPF", "PQC"));
            AddNode("GMF", ("KLR", "VTD"));
            AddNode("JVM", ("TXL", "XTR"));
            AddNode("BLC", ("MNJ", "VFF"));
            AddNode("VTH", ("TGC", "MRH"));
            AddNode("JHB", ("BPN", "DPF"));
            AddNode("TMJ", ("PND", "MLS"));
            AddNode("PFH", ("HSS", "FPK"));
            AddNode("TDG", ("KJV", "QTR"));
            AddNode("TGC", ("TFF", "CJR"));
            AddNode("TVD", ("CCT", "FBF"));
            AddNode("TKX", ("FCT", "CDT"));
            AddNode("BKS", ("HLG", "SFK"));
            AddNode("CGJ", ("NXQ", "BPC"));
            AddNode("QHN", ("SKG", "CKF"));
            AddNode("CVJ", ("DMD", "HQG"));
            AddNode("BMN", ("JLD", "NHG"));
            AddNode("GRP", ("NDL", "NDL"));
            AddNode("FTX", ("BBP", "SCK"));
            AddNode("DXC", ("PPP", "HGT"));
            AddNode("NJD", ("XSP", "KSC"));
            AddNode("CST", ("RRQ", "TKX"));
            AddNode("SVH", ("JHC", "PPH"));
            AddNode("JTV", ("GCM", "RLG"));
            AddNode("BXJ", ("DVD", "FCF"));
            AddNode("HCV", ("XDT", "SSK"));
            AddNode("RDL", ("LQR", "VPM"));
            AddNode("PSG", ("MFS", "MFC"));
            AddNode("MVQ", ("DRH", "QBX"));
            AddNode("XCF", ("FVM", "VVS"));
            AddNode("DXB", ("KSF", "LFJ"));
            AddNode("GHN", ("JGH", "FGR"));
            AddNode("KLJ", ("LSL", "QJJ"));
            AddNode("DFH", ("NNP", "PBL"));
            AddNode("CDL", ("XBG", "FGD"));
            AddNode("VFF", ("KGR", "FCJ"));
            AddNode("KBD", ("FBF", "CCT"));
            AddNode("NJL", ("JGH", "FGR"));
            AddNode("VHG", ("MBT", "XPT"));
            AddNode("GKB", ("GJB", "JKK"));
            AddNode("KQP", ("CXQ", "NGS"));
            AddNode("VSX", ("GDC", "VKQ"));
            AddNode("RHX", ("CDL", "RGD"));
            AddNode("NTK", ("QCC", "QCC"));
            AddNode("KFD", ("SKK", "HGC"));
            AddNode("ZZZ", ("VFF", "MNJ"));
            AddNode("JLK", ("HPL", "MDF"));
            AddNode("BTB", ("PFT", "CCD"));
            AddNode("HQG", ("GFG", "FDP"));
            AddNode("FVM", ("VHC", "NGC"));
            AddNode("CVD", ("NQP", "FXM"));
            AddNode("VGH", ("CCV", "GNG"));
            AddNode("LSV", ("NLJ", "MHQ"));
            AddNode("PVX", ("KGG", "CVJ"));
            AddNode("THL", ("NJL", "GHN"));
            AddNode("KKM", ("XGR", "LLK"));
            AddNode("XGR", ("LRT", "DFP"));
            AddNode("RRN", ("TPM", "XTP"));
            AddNode("GBP", ("GTD", "QSL"));
            AddNode("KJV", ("MDD", "QKK"));
            AddNode("TBN", ("TLV", "JLK"));
            AddNode("LDG", ("TPN", "BCL"));
            AddNode("JLD", ("CJT", "VVD"));
            AddNode("DKN", ("CXQ", "NGS"));
            AddNode("DGV", ("HCV", "NCD"));
            AddNode("HRL", ("QHN", "KNV"));
            AddNode("RRM", ("CLD", "TQC"));
            AddNode("RJS", ("MGH", "VHG"));
            AddNode("MFF", ("QTV", "GJF"));
            AddNode("PNR", ("BTT", "TVN"));
            AddNode("JKK", ("RVV", "XPG"));
            AddNode("XKQ", ("PQT", "FJD"));
            AddNode("RMK", ("JPF", "PQC"));
            AddNode("LCD", ("RJS", "BGP"));
            AddNode("QTK", ("GJG", "HHN"));
            AddNode("TBK", ("CVB", "JVM"));
            AddNode("VTG", ("GMX", "KQX"));
            AddNode("GFG", ("PFR", "GFP"));
            AddNode("RSG", ("LFV", "LFV"));
            AddNode("VCS", ("PCH", "TJR"));
            AddNode("LJC", ("QXF", "XQR"));
            AddNode("QHD", ("XFM", "LQM"));
            AddNode("TSD", ("PPB", "TPQ"));
            AddNode("RHP", ("MXX", "MTC"));
            AddNode("GLZ", ("JSV", "XFL"));
            AddNode("NXD", ("VQJ", "RRS"));
            AddNode("MTJ", ("QJJ", "LSL"));
            AddNode("XQH", ("NQP", "FXM"));
            AddNode("GLK", ("XCX", "NDQ"));
            AddNode("LSL", ("NVS", "TSD"));
            AddNode("QGC", ("LHX", "LHT"));
            AddNode("RHF", ("GHM", "TBT"));
            AddNode("TQR", ("FQD", "FPV"));
            AddNode("QSC", ("XCX", "NDQ"));
            AddNode("RKS", ("JXX", "XSH"));
            AddNode("HGC", ("DCG", "GDD"));
            AddNode("XNV", ("VQG", "PVR"));
            AddNode("CCS", ("RMM", "CLB"));
            AddNode("RVR", ("SJH", "FQT"));
            AddNode("JCM", ("BKS", "PJM"));
            AddNode("GHM", ("FCS", "RCC"));
            AddNode("PFT", ("FCG", "GPJ"));
            AddNode("XDJ", ("DTS", "JVG"));
            AddNode("RVQ", ("FQC", "PLV"));
            AddNode("LQM", ("RMH", "XDJ"));
            AddNode("CKV", ("SJQ", "CTR"));
            AddNode("HPH", ("TLX", "RQG"));
            AddNode("MTC", ("FFX", "DPG"));
            AddNode("CKJ", ("BQP", "DXC"));
            AddNode("MXT", ("CFF", "XFB"));
            AddNode("VHT", ("MQG", "GTH"));
            AddNode("QJJ", ("TSD", "NVS"));
            AddNode("HNA", ("DHL", "XFS"));
            AddNode("PVS", ("TDG", "SLR"));
            AddNode("FPV", ("GMD", "GTK"));
            AddNode("DDG", ("TVR", "JBG"));
            AddNode("BHD", ("LLN", "FCD"));
            AddNode("LDF", ("NNQ", "PKB"));
            AddNode("CKF", ("XXD", "MJL"));
            AddNode("TJF", ("NRG", "HDK"));
            AddNode("JDT", ("BLC", "BLC"));
            AddNode("GXR", ("MGP", "FNX"));
            AddNode("BPS", ("XNF", "MXR"));
            AddNode("FXB", ("QSL", "GTD"));
            AddNode("TLH", ("HGC", "SKK"));
            AddNode("PKV", ("NCD", "HCV"));
            AddNode("CBM", ("NXD", "GTR"));
            AddNode("JNT", ("GJG", "HHN"));
            AddNode("TCQ", ("JTD", "GFC"));
            AddNode("MRS", ("TJX", "DQD"));
            AddNode("FBP", ("VGN", "HNP"));
            AddNode("HPC", ("MRS", "LTC"));
            AddNode("TJX", ("PKV", "DGV"));
            AddNode("LFV", ("MJV", "MJV"));
            AddNode("XVM", ("SQF", "TJF"));
            AddNode("VVF", ("PGV", "RPS"));
            AddNode("XPG", ("DGF", "DJK"));
            AddNode("RGD", ("XBG", "FGD"));
            AddNode("GMC", ("QXT", "CGJ"));
            AddNode("CFM", ("VVF", "QPN"));
            AddNode("SPS", ("QHN", "KNV"));
            AddNode("JTL", ("MNM", "PTS"));
            AddNode("MNM", ("SXH", "BDT"));
            AddNode("RGG", ("LNS", "JQJ"));
            AddNode("FPN", ("GCV", "FXH"));
            AddNode("XJR", ("KCP", "HJS"));
            AddNode("FQN", ("LQX", "MVF"));
            AddNode("CFF", ("JRN", "RDD"));
            AddNode("KSC", ("QGH", "LPG"));
            AddNode("BHB", ("DMR", "JTX"));
            AddNode("TBT", ("RCC", "FCS"));
            AddNode("SKM", ("VVF", "QPN"));
            AddNode("PVR", ("PVS", "PQQ"));
            AddNode("QDN", ("XMK", "JDV"));
            AddNode("JXX", ("STX", "QST"));
            AddNode("TXL", ("LKK", "NSD"));
            AddNode("XTR", ("NSD", "LKK"));
            AddNode("VKQ", ("HXH", "TBK"));
            AddNode("FQX", ("JSK", "LFR"));
            AddNode("FRM", ("CCV", "GNG"));
            AddNode("AAA", ("MNJ", "VFF"));
            AddNode("BKQ", ("NHG", "JLD"));
            AddNode("DPQ", ("MGT", "LXL"));
            AddNode("KXL", ("VQC", "VSX"));
            AddNode("RVV", ("DGF", "DGF"));
            AddNode("TQC", ("NTK", "PFV"));
            AddNode("NPX", ("GJH", "TGL"));
            AddNode("MGH", ("XPT", "MBT"));
            AddNode("VMR", ("HGG", "RHX"));
            AddNode("DCG", ("CLF", "GBS"));
            AddNode("CVB", ("TXL", "XTR"));
            AddNode("HPJ", ("MLS", "PND"));
            AddNode("NNR", ("GDV", "TVB"));
            AddNode("RVX", ("MND", "LLL"));
            AddNode("BVL", ("SKM", "CFM"));
            AddNode("RFS", ("XQR", "QXF"));
            AddNode("TVR", ("XBP", "FPN"));
            AddNode("VTD", ("LTN", "BXH"));
            AddNode("GPC", ("XHK", "BMP"));
            AddNode("QGH", ("RNB", "VSM"));
            AddNode("GDR", ("PJH", "JHB"));
            AddNode("RMG", ("KXL", "TBV"));
            AddNode("PST", ("TVP", "FSV"));
            AddNode("GPJ", ("GXC", "PLG"));
            AddNode("LBD", ("KTN", "GVD"));
            AddNode("LLK", ("LRT", "DFP"));
            AddNode("KGR", ("MVQ", "LKQ"));
            AddNode("MQG", ("XJL", "NHN"));
            AddNode("QXF", ("NSH", "STD"));
            AddNode("GMD", ("PFH", "BQR"));
            AddNode("BFS", ("KGN", "QHD"));
            AddNode("RCR", ("FVM", "VVS"));
            AddNode("RPP", ("SPG", "FHQ"));
            AddNode("FMK", ("BGP", "RJS"));
            AddNode("FGR", ("RMG", "VHP"));
            AddNode("SXH", ("RTB", "LFS"));
            AddNode("GVD", ("GRP", "TCF"));
            AddNode("TGX", ("XFH", "VLS"));
            AddNode("JTD", ("NCJ", "TBN"));
            AddNode("MFV", ("PJH", "JHB"));
            AddNode("HGV", ("KCP", "HJS"));
            AddNode("HSS", ("XKQ", "RGS"));
            AddNode("PTS", ("BDT", "SXH"));
            AddNode("XSP", ("LPG", "QGH"));
            AddNode("TCX", ("PVX", "XVF"));
            AddNode("LKQ", ("QBX", "DRH"));
            AddNode("FSF", ("LSV", "MKG"));
            AddNode("XJQ", ("RHP", "NXM"));
            AddNode("NHN", ("FTX", "DXR"));
            AddNode("GQJ", ("KQP", "DKN"));
            AddNode("TLX", ("XQH", "CVD"));
            AddNode("HJJ", ("VCS", "NKS"));
            AddNode("GTR", ("VQJ", "RRS"));
            AddNode("RHD", ("FJR", "RVR"));
            AddNode("VXK", ("LSV", "MKG"));
            AddNode("MNX", ("HBT", "CLM"));
            AddNode("PPH", ("LVB", "MRB"));
            AddNode("GDP", ("LCB", "GDK"));
            AddNode("DJQ", ("BVL", "RQS"));
            AddNode("FCJ", ("MVQ", "LKQ"));
            AddNode("VHC", ("VHT", "BSP"));
            AddNode("PVL", ("PPR", "SSP"));
            AddNode("LCB", ("DVX", "RKS"));
            AddNode("PFD", ("MNM", "PTS"));
            AddNode("MVF", ("KBD", "TVD"));
            AddNode("DJK", ("XQQ", "TVF"));
            AddNode("QSL", ("GSV", "KCF"));
            AddNode("NXM", ("MXX", "MTC"));
            AddNode("TJT", ("CKJ", "MVG"));
            AddNode("GTH", ("NHN", "XJL"));
            AddNode("SQK", ("SPP", "JCM"));
            AddNode("DPH", ("LNS", "JQJ"));
            AddNode("QPN", ("RPS", "PGV"));
            AddNode("SRK", ("MFX", "CVC"));
            AddNode("RFJ", ("GKB", "TSX"));
            AddNode("QLG", ("XVF", "PVX"));
            AddNode("QTV", ("HLR", "VLL"));
            AddNode("PLV", ("GBX", "RGQ"));
            AddNode("GHR", ("SVH", "JPC"));
            AddNode("XMV", ("GHM", "TBT"));
            AddNode("PKG", ("JDT", "JDT"));
            AddNode("MGP", ("RPG", "QGC"));
            AddNode("QDH", ("TKX", "RRQ"));
            AddNode("HJR", ("RBP", "RVX"));
            AddNode("NDV", ("LCB", "GDK"));
            AddNode("KRV", ("MVF", "LQX"));
            AddNode("NTM", ("TJF", "SQF"));
            AddNode("NXQ", ("BKQ", "BMN"));
            AddNode("HFF", ("VDT", "JSL"));
            AddNode("SLR", ("QTR", "KJV"));
            AddNode("DDN", ("BKK", "FNM"));
            AddNode("LHT", ("XJQ", "GRM"));
            AddNode("DST", ("QKX", "FNK"));
            AddNode("PPR", ("MNV", "HTF"));
            AddNode("JHC", ("LVB", "MRB"));
            AddNode("MXX", ("DPG", "FFX"));
            AddNode("VDT", ("DDN", "DDN"));
            AddNode("XMC", ("HBT", "CLM"));
            AddNode("TPD", ("SSP", "PPR"));
            AddNode("BSP", ("GTH", "MQG"));
            AddNode("NJG", ("FCH", "CSP"));
            AddNode("MGT", ("VGH", "FRM"));
            AddNode("NCJ", ("TLV", "JLK"));
            AddNode("VCN", ("NSB", "CLC"));
            AddNode("CBD", ("CCD", "PFT"));
            AddNode("NQB", ("XHK", "BMP"));
            AddNode("MFG", ("XNF", "MXR"));
            AddNode("XFL", ("RMR", "QFK"));
            AddNode("KCF", ("JNT", "QTK"));
            AddNode("JTX", ("MKB", "NGM"));
            AddNode("NTG", ("MBK", "CGX"));
            AddNode("XCX", ("MBR", "RDL"));
            AddNode("HGT", ("HPP", "DLP"));
            AddNode("FJD", ("GHP", "SQK"));
            AddNode("FXF", ("PFP", "FRL"));
            AddNode("GFC", ("TBN", "NCJ"));
            AddNode("NSD", ("HFR", "FBP"));
            AddNode("HJS", ("DDG", "GFF"));
            AddNode("MNV", ("RQV", "VLX"));
            AddNode("VRH", ("MTJ", "KLJ"));
            AddNode("GJH", ("XRF", "TGX"));
            AddNode("JMM", ("BHB", "VJK"));
            AddNode("BDN", ("RBK", "RRN"));
            AddNode("JDP", ("BLC", "ZZZ"));
            AddNode("GJK", ("HHB", "DNX"));
            AddNode("TCF", ("NDL", "HFF"));
            AddNode("JGV", ("MFK", "MRL"));
            AddNode("LPG", ("VSM", "RNB"));
            AddNode("KBH", ("FTV", "LBD"));
            AddNode("CDT", ("NXN", "GQP"));
            AddNode("QKK", ("GGR", "LXC"));
            AddNode("RMD", ("CJF", "XNV"));
            AddNode("MKF", ("TVN", "BTT"));
            AddNode("RBV", ("XSP", "KSC"));
            AddNode("RMH", ("JVG", "DTS"));
            AddNode("RPG", ("LHT", "LHX"));
            AddNode("FCH", ("NDV", "GDP"));
            AddNode("HPF", ("LTS", "RVQ"));
            AddNode("DRH", ("BTM", "HPH"));
            AddNode("PFR", ("RJR", "DBR"));
            AddNode("RJR", ("SVN", "VXJ"));
            AddNode("MFK", ("HCQ", "QDN"));
            AddNode("RGQ", ("VRH", "CPG"));
            AddNode("BSX", ("GHN", "NJL"));
            AddNode("TLR", ("XFL", "JSV"));
            AddNode("KCV", ("NQF", "BCH"));
            AddNode("PJC", ("JGX", "JCV"));
            AddNode("XVF", ("KGG", "CVJ"));
            AddNode("DKF", ("GBP", "FXB"));
            AddNode("SKG", ("XXD", "MJL"));
            AddNode("MVB", ("BVP", "BXM"));
            AddNode("MJL", ("GJK", "CVV"));
            AddNode("NSH", ("VCN", "VXF"));
            AddNode("DVD", ("BCQ", "PJC"));
            AddNode("VPR", ("LLN", "FCD"));
            AddNode("HLG", ("SDF", "HPF"));
            AddNode("FLD", ("BXJ", "DTM"));
            AddNode("SKK", ("GDD", "DCG"));
            AddNode("NQF", ("SRK", "LSG"));
            AddNode("QNN", ("LXL", "MGT"));
            AddNode("DMR", ("MKB", "NGM"));
            AddNode("FVB", ("NNR", "PBH"));
            AddNode("MXR", ("TPD", "PVL"));
            AddNode("CLF", ("DJC", "XXQ"));
            AddNode("FCT", ("GQP", "NXN"));
            AddNode("RPA", ("QKX", "FNK"));
            AddNode("MHQ", ("XCF", "RCR"));
            AddNode("XPK", ("PBH", "NNR"));
            AddNode("RBK", ("TPM", "TPM"));
            AddNode("LVX", ("TDQ", "XLH"));
            AddNode("RMR", ("SDM", "VTH"));
            AddNode("PBF", ("FNX", "MGP"));
            AddNode("GCM", ("QML", "XGD"));
            AddNode("KSF", ("BSX", "THL"));
            AddNode("XXD", ("GJK", "CVV"));
            AddNode("DBR", ("VXJ", "SVN"));
            AddNode("THD", ("DXB", "GDQ"));
            AddNode("LFR", ("LBC", "CPT"));
            AddNode("LKK", ("FBP", "HFR"));
            AddNode("GFP", ("RJR", "DBR"));
            AddNode("RNK", ("VCS", "NKS"));
            AddNode("PBL", ("VNQ", "SRD"));
            AddNode("FXM", ("DDF", "LVX"));
            AddNode("KGN", ("XFM", "LQM"));
            AddNode("VPK", ("GPC", "NQB"));
            AddNode("JNS", ("HGV", "XJR"));
            AddNode("GTK", ("BQR", "PFH"));
            AddNode("FTV", ("KTN", "GVD"));
            AddNode("MCJ", ("DFH", "GGQ"));
            AddNode("MDF", ("LJC", "RFS"));
            AddNode("JRL", ("GJF", "QTV"));
            AddNode("MFC", ("RMK", "JBX"));
            AddNode("VVS", ("NGC", "VHC"));
            AddNode("TVF", ("TLR", "GLZ"));
            AddNode("FCF", ("BCQ", "PJC"));
            AddNode("SXS", ("NQF", "BCH"));
            AddNode("GDC", ("HXH", "TBK"));
            AddNode("XXQ", ("MKF", "PNR"));
            AddNode("SPG", ("GMR", "TRF"));
            AddNode("GVP", ("LNN", "TJT"));
            AddNode("PQQ", ("SLR", "TDG"));
            AddNode("HBT", ("QRH", "LDG"));
            AddNode("XGD", ("KSR", "RFJ"));
            AddNode("QML", ("KSR", "RFJ"));
            AddNode("LKM", ("RVR", "FJR"));
            AddNode("DRN", ("MJV", "NFS"));
            AddNode("MKB", ("NTF", "BDN"));
            AddNode("GHP", ("JCM", "SPP"));
            AddNode("XPT", ("JMM", "CBB"));
            AddNode("KTN", ("GRP", "TCF"));
            AddNode("LRT", ("SCN", "HJR"));
            AddNode("BVP", ("QKT", "GHR"));
            AddNode("FNK", ("VPR", "BHD"));
            AddNode("GRM", ("RHP", "NXM"));
            AddNode("BXM", ("QKT", "GHR"));
            AddNode("CPM", ("RSG", "NCR"));
            AddNode("MRL", ("HCQ", "QDN"));
            AddNode("VQG", ("PVS", "PQQ"));
            AddNode("STD", ("VXF", "VCN"));
            AddNode("DQD", ("DGV", "PKV"));
            AddNode("TSX", ("GJB", "JKK"));
            AddNode("GTD", ("KCF", "GSV"));
            AddNode("FNX", ("RPG", "QGC"));
            AddNode("BXH", ("LDF", "FHF"));
            AddNode("CVC", ("GLK", "QSC"));
            AddNode("TLV", ("MDF", "HPL"));
            AddNode("DNL", ("PMG", "VRK"));
            AddNode("FQD", ("GTK", "GMD"));
            AddNode("CPG", ("MTJ", "KLJ"));
            AddNode("SPP", ("BKS", "PJM"));
            AddNode("GJB", ("RVV", "XPG"));
            AddNode("SSK", ("FXF", "BTN"));
            AddNode("PVH", ("MXT", "JDF"));
            AddNode("XVN", ("FQN", "KRV"));
            AddNode("LFJ", ("BSX", "THL"));
            AddNode("VNH", ("KGN", "QHD"));
            AddNode("HLR", ("FMK", "LCD"));
            AddNode("KBL", ("JTL", "PFD"));
            AddNode("BTM", ("TLX", "RQG"));
            AddNode("DPB", ("PST", "DVS"));
            AddNode("LTS", ("FQC", "PLV"));
            AddNode("RQG", ("CVD", "XQH"));
            AddNode("PBR", ("LNN", "TJT"));
            AddNode("CLB", ("MFG", "BPS"));
            AddNode("XFM", ("RMH", "XDJ"));
            AddNode("CJR", ("MJQ", "MVB"));
            AddNode("VTN", ("BVL", "RQS"));
            AddNode("VBG", ("QDH", "CST"));
            AddNode("GMR", ("HVJ", "DKF"));
            AddNode("KHG", ("BXJ", "DTM"));
            AddNode("GDD", ("CLF", "GBS"));
            AddNode("QTR", ("QKK", "MDD"));
            AddNode("VCL", ("MFS", "MFC"));
            AddNode("TBV", ("VQC", "VSX"));
            AddNode("BCQ", ("JCV", "JGX"));
            AddNode("NGC", ("VHT", "BSP"));
            AddNode("GJF", ("HLR", "VLL"));
            AddNode("FGD", ("NPX", "BHV"));
            AddNode("RGS", ("PQT", "FJD"));
            AddNode("VXJ", ("PBF", "GXR"));
            AddNode("FJR", ("SJH", "FQT"));
            AddNode("VXF", ("CLC", "NSB"));
            AddNode("HCF", ("GPC", "NQB"));
            AddNode("DTK", ("RLG", "GCM"));
            AddNode("MRB", ("XMC", "MNX"));
            AddNode("MFX", ("QSC", "GLK"));
            AddNode("GMX", ("VXK", "FSF"));
            AddNode("BDT", ("LFS", "RTB"));
            AddNode("JRN", ("VHQ", "JGB"));
            AddNode("SHJ", ("KLR", "VTD"));
            AddNode("TCL", ("HRL", "SPS"));
            AddNode("CPT", ("DTK", "JTV"));
            AddNode("VPM", ("TFH", "RRM"));
            AddNode("DQP", ("RMD", "KVX"));
            AddNode("CJF", ("VQG", "PVR"));
            AddNode("PBH", ("GDV", "TVB"));
            AddNode("LXC", ("QLG", "TCX"));
            AddNode("FHQ", ("GMR", "TRF"));
            AddNode("BMP", ("XVM", "NTM"));
            AddNode("XHK", ("NTM", "XVM"));
            AddNode("NQP", ("LVX", "DDF"));
            AddNode("TVP", ("GMC", "HJN"));
            AddNode("XFS", ("LNH", "RPP"));
            AddNode("RGM", ("RHX", "HGG"));
            AddNode("NQC", ("VNH", "BFS"));
            AddNode("GXC", ("RBV", "NJD"));
            AddNode("XQR", ("NSH", "STD"));
            AddNode("BTT", ("QNN", "DPQ"));
            AddNode("PFP", ("CHS", "JNV"));
            AddNode("QKT", ("SVH", "JPC"));
            AddNode("QCC", ("DHL", "XFS"));
            AddNode("LTN", ("LDF", "FHF"));
            AddNode("CMR", ("GMJ", "NJG"));
            AddNode("DGF", ("XQQ", "XQQ"));
            AddNode("MTX", ("DST", "BJZ"));
            AddNode("QSJ", ("GTR", "NXD"));
            AddNode("DFP", ("HJR", "SCN"));
            AddNode("MNJ", ("FCJ", "KGR"));
            AddNode("XSH", ("QST", "STX"));
            AddNode("VHP", ("KXL", "TBV"));
            AddNode("DGS", ("KQP", "DKN"));
            AddNode("HPL", ("LJC", "RFS"));
            AddNode("DTS", ("RDG", "PBT"));
            AddNode("VJK", ("JTX", "DMR"));
            AddNode("CLM", ("LDG", "QRH"));
            AddNode("QFK", ("SDM", "VTH"));
            AddNode("HGG", ("CDL", "RGD"));
        }
    }
}